### ISSUE TITLE
Does this program support Synology 7.0.1?

### ISSUE THREAD

**Issue by zailushang2008** [ksk0/cpu-fan#1]
Linux ontheroad 4.4.180+ #42218 SMP Mon Oct 18 19:17:56 CST 2021 x86_64 GNU/Linux synology_apollolake_918+

**Comment by ksk0** [comment]
I honestly have no experience with Synology NAS servers. But, as stated in README, if there is a chip controlled by **nct6775** kernel module, there is a chance that it will work. This is not a program that controls a fan, it is a script that sets registers on motherboard (for which **nct6775** module is necessary), and motherboard itself will control the fan speed.

Follow the installation instructions and try. If it does not work, just uninstall the script.

**Comment by zailushang2008** [comment]
Thank you for your answer,i will try.
